import {View, Dimensions, StyleSheet} from 'react-native';
import React from 'react';

const styles = StyleSheet.create({
  coverUserCommentSection: {
    width: '100%',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',

    height: 60,
    borderBottomColor: '#d1d1d1',
    borderBottomWidth: 0,
  },
  sortText: {
    color: '#3b3b3b',
    marginLeft: 10,
    fontSize: 16,
  },
  groupImg: {
    height: 350,
    width: '100%',
    marginTop: -18,
    backgroundColor: '#0a171e',
  },
  scrollViewCover: {
    padding: 16,
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
  },
  personalInfo: {
    color: '#111',
    fontSize: 24,
    fontWeight: '500',
    marginVertical: 18,
  },
  sectionBG: {
    // backgroundColor: '#aaaaaa18',
    backgroundColor: '#efefef',
    paddingHorizontal: 20,
    paddingVertical: 10,
    width: '100%',
  },
  groupBy: {
    color: '#aaa',
    fontFamily: 'Overpass-Regular',
  },
  amassName: {
    fontWeight: 'bold',
    fontSize: 23,
    color: '#000',
  },
  //   eachNameCover: {
  //     borderBottomColor: '#cccccc89',
  //     borderBottomWidth: 2,
  //     paddingBottom: 3,
  //     marginTop: 10,
  //   },
  bestOfOur: {flexDirection: 'row', marginVertical: 10, alignItems: 'center'},
  bestOfOurText: {
    color: '#26262689',
    fontSize: 13,
    fontWeight: 'bold',
    fontFamily: 'Overpass-Regular',
    marginLeft: 8,
  },
  BTN: {
    // backgroundColor: '#e20154',
    backgroundColor: '#e20154',
    flexDirection: 'row',
    width: 120,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    shadowOffset: {width: -2, height: 4},
    shadowColor: '#171717',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowColor: '#000',
    elevation: 1,
  },
  labelStyle: {
    color: '#fff',
    fontWeight: 'bold',
    marginLeft: 5,
  },
  suggestedText: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  smallFollowing: {
    color: '#555555',
    fontSize: 9,
    fontFamily: 'Overpass-Regular',
    marginBottom: 1,
  },
  btnCover: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#7c90b069',
  },
  lineBottom: {
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#7c90b069',
  },
  activityCover: {
    backgroundColor: '#fff',
    width: '100%',
    // height: '100%',
    marginVertical: 30,
    paddingBottom: 30,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  pleaseRetry: {
    color: '#000',
    fontFamily: 'Overpass-Regular',
    textAlign: 'center',
  },
  commentOwner: {
    fontWeight: 'bold',
    color: '#3b3b3b',
    fontSize: 16,
    textAlign: 'left',
    paddingLeft: 20,
  },
  topText: {fontWeight: '400', color: 'rgb(112, 122, 138)', fontSize: 12},
  bottomBtnColor: {
    marginTop: 'auto',
    width: '100%',
    borderTopColor: '#ccc',
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderTopWidth: 1,
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
  },
  smallBgColor: {
    backgroundColor: '#00000011',
    borderRadius: 7,
    overflow: 'hidden',
    position: 'relative',
  },
  coverNot: {
    flexDirection: 'row',
    marginBottom: 10,
    alignItems: 'center',
    position: 'absolute',
    top: 11,
    left: 6,
    width: '100%',
    marginTop: 6,
    zIndex: 20,
    paddingLeft: 10,
  },
  loadingImg: {
    width: 42,
    height: 42,
    overflow: 'hidden',
    borderRadius: 50,
    borderBottomEndRadius: 20,
    marginRight: 10,
  },
  coverStatusRound: {
    marginRight: 3,
    padding: 2,
    borderRadius: 100,
    borderWidth: 1,
    borderTopColor: '#fff',
    borderBottomColor: '#9e005d98',
    borderBottomEndRadius: 30,
    // botop
    borderRightColor: '#9e005d',
  },
  styleImage: {
    width: 42,
    height: 42,
    borderRadius: 50,
  },
  isActive: {
    width: 13,
    height: 13,
    backgroundColor: '#3cca0b',
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 20,
    position: 'absolute',
    top: 7,
    left: -4,
  },
  bottomDone: {
    borderTopColor: '#00000022',
    borderTopWidth: 1,
    marginTop: 9,
    width: '100%',
    height: 116,
    position: 'relative',
  },
  isBlur: {
    position: 'absolute',
    zIndex: 20,
    backgroundColor: '#99999933',
    width: '180%',
    height: '100%',
    left: -40,
    top: 0,
  },
  mappedDatasCover: {
    position: 'relative',
    marginVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 3,
    overflow: 'hidden',
  },
  mappedDatasCoverFullname: {
    fontWeight: 'bold',
    fontSize: 11,
    fontFamily: 'Overpass-Regular',
    textTransform: 'capitalize',
    color: '#000',
  },
  mappedDatasCoverUsername: {
    fontSize: 13,
    // textTransform: 'lowercase',
    fontFamily: 'Overpass-Regular',
    color: '#777',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: Dimensions.get('window').height,
    // marginTop: 22,
    backgroundColor: '#00000066',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 7,
    height: '100%',
    padding: 15,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },

  flexCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  headerOne: {
    color: 'rgb(30, 35, 41)',
    fontWeight: 'bold',
    fontSize: 18,
    marginLeft: 5,
    // fontFamily: 'Overpass-Regular',
    fontFamily: 'Rajdhani-Regular',

    marginRight: 2,
  },
  messageInput: {
    height: 180,
    color: '#000',
    justifyContent: 'flex-start',
  },
  coverSearchHere: {
    backgroundColor: '#efefef',
    width: '100%',
    paddingHorizontal: 20,
    borderRadius: 5,
    height: 45,
    marginTop: 20,
    marginBottom: 9,
    overflow: 'hidden',
    alignItems: 'center',
    flexDirection: 'row',
  },
  innerTextInput: {
    color: '#262626',
    marginLeft: 10,
    fontFamily: 'Overpass-Regular',
    width: '100%',
  },
  coverTag: {
    position: 'absolute',
    right: 0,
    height: '100%',
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  coverTagged: {
    backgroundColor: '#fff',
    width: '100%',
    height: '100%',
    zIndex: 10,
    top: 30,
  },
  centerImage: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 60,
  },

  mappedHorizontalCover: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    position: 'relative',
  },
  mappedHorizontalSemiCover: {
    position: 'absolute',
    top: 0,
    zIndex: 10,
    right: 5,
    width: 37,
    height: 37,
  },
  mappedHorizontalSemiSemiCover: {
    borderWidth: 2,
    borderColor: '#eee',
    height: 24,
    width: 24,
    marginLeft: 'auto',
    backgroundColor: '#fff',
    zIndex: 10,
    borderRadius: 19,
  },
  bottomSideCover: {
    width: 110,
    height: '57%',
    position: 'absolute',
    zIndex: 12,
    right: 0,
    top: 3,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  bottomSideCoverText: {
    fontFamily: 'Overpass-Regular',
    fontSize: 10,
    fontWeight: 'bold',
    color: '#00000062',
  },
  boxStuff: {
    width: 33,
    height: 33,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    backgroundColor: '#e20154',
  },
  closeLine: {
    position: 'absolute',
    top: 8,
    right: 5,
    backgroundColor: '#e1e1e1',
    width: 34,
    height: 34,
    borderRadius: 20,
    alignItems: 'center',
    marginLeft: 'auto',
    justifyContent: 'center',
  },
  anocenteredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: Dimensions.get('window').height,
    backgroundColor: '#00000066',
  },
  anomodalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 7,
    padding: 15,
    width: '90%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  textAreaStyle: {
    // borderBottomColor: '#e2015429',
    borderBottomColor: '#00000022',
    borderBottomWidth: 1,
    marginBottom: 15,
  },
});
export default styles;
