import {View, Dimensions, StyleSheet} from 'react-native';
import React from 'react';

const styles = StyleSheet.create({
  iCoverSearchHere: {
    backgroundColor: '#202d34',
    width: '100%',
    paddingHorizontal: 20,
    borderRadius: 5,
    height: 45,
    alignItems: 'center',
    flexDirection: 'row',
  },
  clearAll: {
    position: 'absolute',
    top: 10,
    right: 10,
    fontWeight: 'bold',
    color: '#fff',
  },
  iInnerTextInput: {
    color: '#abb1b8',
    marginLeft: 10,
    width: '80%',
  },
  coverAnt: {
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#7c90b0',
    marginBottom: 20,
    flexDirection: 'row',
  },
  container: {
    width: '100%',
    backgroundColor: '#fff',
    height: '100%',
    flex: 1,
  },
  firstVersion: {
    width: '100%',
    paddingLeft: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  hiCover: {
    marginTop: 10,
    color: '#222',
    fontSize: 30,
    paddingVertical: 6,
    fontWeight: 'bold',
    fontFamily: 'Optimistic Display',
  },
  secondVersionBody: {
    color: '#555555',

    fontFamily: 'Optimistic Display',
  },
  imageHere: {
    width: 390,
    margin: 'auto',
    alignSelf: 'center',
    marginTop: 40,
    height: 290,
  },
  backgroundVideoCover: {
    width: '100%',
    height: 400,
  },
  backgroundVideo: {
    // position: 'absolute',
    // top: 0,
    // bottom: 0,
    // left: 0,
    // right: 0,
    width: '100%',
    height: '100%',
    // margin: 'auto',
  },
  coverAllAboutVideo: {
    width: '100%',
    paddingHorizontal: 23,
    // backgroundColor: "red",
  },
  editIconHereCover: {
    width: 140,
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    borderWidth: 2,
    // borderColor: '#9e005d',
    borderColor: '#e20154',
    color: '#e20154',
    fontWeight: 'bold',
    borderRadius: 5,
    backgroundColor: 'transparent',
  },
  pausedIcon: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  setIsCover: {
    marginLeft: 8,
    marginTop: 2,
  },
  selectedFileName: {
    // position: 'absolute',
    // bottom: -57,
    // right: 10,
    color: '#000',
  },
  textAreaStyleCover: {
    marginTop: 2,
    width: '100%',
  },
  textAreaStyle: {
    // borderBottomColor: '#e2015429',
    borderBottomColor: '#00000022',
    borderBottomWidth: 1,
    marginBottom: 15,
  },
  pleaseRetry: {
    color: '#000',
    fontFamily: 'Overpass-Regular',
    textAlign: 'center',
  },
  messageInput: {
    height: 180,
    color: '#000',
    justifyContent: 'flex-start',
  },
  coverSearchHere: {
    backgroundColor: '#efefef',
    width: '100%',
    paddingHorizontal: 20,
    borderRadius: 5,
    height: 45,
    // marginTop: 20,
    marginBottom: 9,
    overflow: 'hidden',
    alignItems: 'center',
    flexDirection: 'row',
  },
  innerTextInput: {
    color: '#262626',
    marginLeft: 10,
    fontFamily: 'Overpass-Regular',
    width: '100%',
  },
  coverTag: {
    position: 'absolute',
    right: 0,
    height: '100%',
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  coverTagged: {
    backgroundColor: '#fff',
    width: '100%',
    height: '100%',
    zIndex: 10,
    top: 30,
  },
  centerImage: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 60,
  },
  DoyouKnow: {
    margin: 'auto',
    width: 270,
    height: 270,
  },
  eachBtnText: {
    color: '#262626',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 15,
  },
  noCoverProgressBaroo: {
    // bottom: 0,
    // left: 0,
    // right: 0,
    top: 0,
    zIndex: 10,
    // alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    flexDirection: 'row',
    width: '100%',
    // backgroundColor: 'red',
    // position: 'absolute',
  },
  bottomSmth: {
    width: '100%',
    height: 90,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#aaaaaa19',
    padding: 10,
  },
  bestOfOur: {flexDirection: 'row', paddingVertical: 12, alignItems: 'center'},
  bestOfOurText: {
    color: '#262626',
    fontSize: 13,
    fontWeight: 'bold',
    fontFamily: 'Overpass-Regular',
    marginLeft: 8,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: Dimensions.get('window').height,
    // marginTop: 22,
    backgroundColor: '#00000066',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 7,
    height: '100%',
    padding: 15,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  flexCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  headerOne: {
    color: 'rgb(30, 35, 41)',
    fontWeight: 'bold',
    fontSize: 18,
    marginLeft: 5,
    // fontFamily: 'Overpass-Regular',
    fontFamily: 'Rajdhani-Regular',

    marginRight: 2,
  },
  styleImage: {
    width: 42,
    height: 42,
    borderRadius: 50,
  },
  clickable: {
    width: 30,
    height: 30,
    borderRadius: 45,
    backgroundColor: 'blue',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
    borderColor: '#00000022',
    borderWidth: 1,
  },
  innerCircle: {
    width: 13,
    marginLeft: 0,
    height: 13,
    backgroundColor: '#fff',
    borderRadius: 30,
  },
  bottomDone: {
    borderTopColor: '#00000022',
    borderTopWidth: 1,
    marginTop: 9,
    width: '100%',
    height: 116,
  },
  smallFollowing: {
    color: '#555555',
    fontSize: 9,
    fontFamily: 'Overpass-Regular',
    marginBottom: 1,
  },
  learnMore: {
    color: 'blue',
    fontSize: 15,
    fontWeight: 'bold',
    marginTop: 0,
    // textAlign: 'center',
  },
  activiityCover: {
    width: '80%',
    height: '100%',
    marginLeft: 'auto',
    marginRight: 'auto',
    // justifyContent: 'center',
    alignItems: 'center',
  },
  dateText: {
    fontFamily: 'Overpass-Regular',
    color: '#9f9f9f',
    fontSize: 14,
  },
  username: {
    color: '#3b3b3b',
    fontWeight: 'bold',
    fontFamily: 'Overpass-Regular',
    fontSize: 18,
  },
  isActive: {
    width: 13,
    height: 13,
    backgroundColor: '#3cca0b',
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 20,
    position: 'absolute',
    top: 7,
    zIndex: 20,
    left: -4,
  },
   coverStatusRound: {
    marginRight: 13,
    padding: 4,
    borderRadius: 100,
    borderWidth: 1,
    borderTopColor: '#fff',
    borderBottomColor: '#9e005d98',
    borderBottomEndRadius: 30,
    // botop
    borderRightColor: '#9e005d',
  },
  mappedDatasCover: {
    marginVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 3,
    overflow: 'hidden',
  },
  loadingImg: {
    width: 42,
    height: 42,
    overflow: 'hidden',
    borderRadius: 50,
    borderBottomEndRadius: 20,
    marginRight: 10,
  },
  mappedDatasCoverFullname: {
    fontWeight: 'bold',
    fontSize: 11,
    fontFamily: 'Overpass-Regular',
    textTransform: 'capitalize',
    color: '#fff',
  },
  mappedDatasCoverUsername: {
    fontSize: 13,
    color: '#ccc',
    textTransform: 'lowercase',
  },
  mappedHorizontalCover: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    position: 'relative',
  },
  mappedHorizontalSemiCover: {
    position: 'absolute',
    top: 0,
    zIndex: 1,
    right: 5,
    width: 37,
    height: 37,
  },
  mappedHorizontalSemiSemiCover: {
    borderWidth: 2,
    borderColor: '#eee',
    height: 24,
    marginLeft: 'auto',
    width: 24,
    borderRadius: 19,
  },
  handleComponentStyle: {
    width: '100%',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    flexDirection: 'row',
    backgroundColor: '#e20154',
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomColor: '#d1d1d1',
    borderBottomWidth: 2,
  },
  closeLine: {
    position: 'absolute',
    right: 15,
    backgroundColor: '#e1e1e1',
    width: 30,
    height: 30,
    borderRadius: 20,
    alignItems: 'center',
    marginLeft: 'auto',
    justifyContent: 'center',
  },

  categoryText: {
    fontWeight: 'bold',
    fontSize: 25,
    textAlign: 'center',
    marginTop: 20,
    color: '#111',
  },
  sortText: {
    color: '#111',
    fontFamily: 'Overpass-Regular',
    fontSize: 16,
  },
  coverUserCommentSection: {
    width: '100%',
    height: 50,
    flexDirection: 'row',
    marginBottom: 10,
    // paddingBottom: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
  },

  anocenteredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: Dimensions.get('window').height,
    // marginTop: 22,
    backgroundColor: '#00000066',
  },
  anomodalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 7,
    // height: "90%",
    padding: 15,
    width: '90%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },

  showAbsolute: {
    position: 'absolute',
    backgroundColor: '#00003330',
    width: '100%',
    height: '100%',
    zIndex: 222,
  },
  reactionText: {
    color: '#000',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  coverMain: {
    flex: 1,
    width: '100%',
    heigth: '100%',
    backgroundColor: '#000',
  },
  activityCover: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    top: 0,
    left: 0,
    backgroundColor: '#0a171e53',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  coverNot: {
    flexDirection: 'row',
    marginBottom: 10,
    alignItems: 'center',
    position: 'relative',
    width: '100%',
    marginTop: 6,
  },

  eachNameCover: {
    borderBottomColor: '#cccccc89',
    borderBottomWidth: 2,
    paddingBottom: 3,
    marginTop: 10,
  },
  upperText: {
    color: '#9f9f9f',
    fontSize: 18,
  },
  mainText: {
    color: '#3b3b3b',
    height: 50,
    width: '100%',
    fontSize: 20,
  },
  viewCover: {
    width: '100%',
    height: 35,
  },
  eachBtnCover: {
    backgroundColor: '#efefef',
    paddingHorizontal: 20,
    borderRadius: 5,
    height: 55,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  comment: {
    color: '#3b3b3b',
    fontSize: 19,
  },
  participantCover: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  headerDesc: {
    fontSize: 13,
    // color: '#e20154',
    color: '#000',
    fontWeight: 'bold',
    fontFamily: 'Overpass-Regular',
  },
  mainUsername: {
    color: '#000000',
    fontSize: 14,
    fontFamily: 'Overpass-Regular',
  },
});
export default styles;
