import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  styleLandingLogo: {
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00000088',
  },
  backTouchableOpacity: {
    width: 40,
    height: 40,
    borderRadius: 50,
    backgroundColor: '#0a171e',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: 40,
    top: 20,
  },
  coverHere: {
    width: '100%',
    padding: 20,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00000088',
  },
  positionAbsoluteView: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    padding: 20,
  },
  whatsYourNumber: {
    fontWeight: 'bold',
    marginBottom: 30,
    fontSize: 30,
    color: '#fff',
  },
  handleComponentStyle: {
    width: '100%',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    flexDirection: 'row',
    backgroundColor: '#e20154',
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomColor: '#d1d1d1',
    borderBottomWidth: 2,
  },
  reactionText: {
    color: '#000',
    textAlign: 'center',
    fontWeight: 'bold',
  },

  showAbsolute: {
    position: 'absolute',
    // backgroundColor: '#d00',
    backgroundColor: '#00003330',
    width: '100%',
    height: '100%',
    zIndex: 2222,
  },

  closeLine: {
    position: 'absolute',
    right: 15,
    backgroundColor: '#e1e1e1',
    width: 30,
    height: 30,
    borderRadius: 20,
    alignItems: 'center',
    marginLeft: 'auto',
    justifyContent: 'center',
  },
  positionAbsolute: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    // backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  textInputLinkCover: {
    width: '100%',
    borderRadius: 5,
    borderWidth: 2,
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#fff',

    overflow: 'hidden',
    backgroundColor: '#fff',
    zIndex: 2000,
  },
  inputTextInput: {
    paddingLeft: 20,
    // marginLeft: 40,
    color: '#3b3b3b',
    width: '100%',
    // backgroundColor: 'red',
    paddingRight: 15,
  },
  eachBtnCover: {
    backgroundColor: '#e20154',
    paddingHorizontal: 20,
    borderRadius: 5,
    height: 55,
    marginTop: 30,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  eachBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 15,
  },
  coverUserCommentSection: {
    width: '100%',
    height: 50,
    flexDirection: 'row',
    marginBottom: 10,
    // paddingBottom: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sortText: {
    color: '#111',
    fontSize: 16,
  },
  coverSearchHere: {
    backgroundColor: '#efefef',
    width: '100%',
    overflow: 'hidden',
    paddingHorizontal: 20,
    borderRadius: 5,
    height: 45,
    alignItems: 'center',
    // justifyContent: 'center',
    flexDirection: 'row',
  },

  innerTextInput: {
    width: '100%',
    color: '#262626',
    marginLeft: 10,
  },
  clickable: {
    width: 30,
    height: 30,
    borderRadius: 45,
    backgroundColor: 'blue',
    alignItems: 'center',
    justifyContent: 'center',

    borderColor: '#9f9f9f',
    borderWidth: 2,
  },
  innerCircle: {
    width: 13,
    marginLeft: 1,
    height: 13,
    backgroundColor: '#fff',
    borderRadius: 30,
  },
  container: {
    flex: 1,
    paddingTop: 200,
  },
  contentContainer: {
    backgroundColor: 'white',
  },
  itemContainer: {
    padding: 6,
    margin: 6,
    backgroundColor: '#eee',
  },
});
export default styles;