import {View, Dimensions, StyleSheet} from 'react-native';
import React from 'react';

const styles = StyleSheet.create({
  coverMain: {
    flex: 1,
    width: '100%',
    heigth: '100%',
    backgroundColor: '#000',
  },
  activityCover: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    top: 0,
    left: 0,
    backgroundColor: '#0a171e53',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  containerCover: {
    width: '100%',
    // flex: 1,
    // height: 30000,
    backgroundColor: '#fff',
    position: 'relative',
  },
  headerHere: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: 55,
    shadowOffset: {width: -2, height: 4},
    shadowColor: '#171717',
    shadowOpacity: 0.2,
    paddingHorizontal: 20,
    shadowRadius: 3,
    shadowColor: '#000',
    elevation: 1,
  },
  headerTextStyle: {
    color: '#3b3b3b',
    fontSize: 19,
    fontFamily: "Gilroy-Bold",
  },
  eachBtnCover: {
    backgroundColor: '#efefef',
    paddingHorizontal: 20,
    borderRadius: 5,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },

  eachBtnText: {
    color: '#262626',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 15,
  },
  showAbsolute: {
    position: 'absolute',
    // backgroundColor: '#e010b400',
    backgroundColor: '#00003330',
    width: '100%',
    height: '100%',
    zIndex: 22,
  },
  handleComponentStyle: {
    width: '100%',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    flexDirection: 'row',
    backgroundColor: '#e20154',
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomColor: '#d1d1d1',
    borderBottomWidth: 2,
  },
  reactionText: {
    color: '#000',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  closeLine: {
    position: 'absolute',
    right: 15,
    backgroundColor: '#e1e1e1',
    width: 30,
    height: 30,
    borderRadius: 20,
    alignItems: 'center',
    marginLeft: 'auto',
    justifyContent: 'center',
  },
  coverFundsHere: {
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 30,
    justifyContent: 'center',
  },
  
});
export default styles;