import {Dimensions, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: Dimensions.get('window').height,
    backgroundColor: 'red',
  },
  videoContainer: {
    backgroundColor: '#000',
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  video: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  coverVideoLoading: {
    backgroundColor: '#00000025',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pausedIcon: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 8,
  },
  Lottie: {
    flex: 1,
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  activityCover: {
    backgroundColor: '#000',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },

  // container: {
  //   width: '100%',
  //   // height: Dimensions.get('window').height,
  //   // height: Dimensions.get('window').height + 25,
  //   // height: Dimensions.get('window').height - 40,
  //   backgroundColor: 'black',
  // },
  // video: {
  //   position: 'absolute',
  //   top: 0,
  //   left: 0,
  //   bottom: 0,
  //   // zIndex: 10,
  //   right: 0,
  // },
  // uiContainer: {
  //   height: '100%',
  //   justifyContent: 'flex-end',
  //   paddingBottom: 24,
  //   position: "absolute",
  // },
  // pausedIcon: {
  //   position: 'absolute',
  //   width: '100%',
  //   height: '100%',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  // {/* bottomContainer Section */}
  handle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  videoDesc: {
    color: '#fff',
    fontSize: 13,
    fontFamily: 'Overpass-Regular',
    fontWeight: '300',
  },
  sponsored: {
    flexDirection: 'row',
    paddingTop: 4,
    alignItems: 'center',
  },
  bottomContainer: {
    padding: 10,
    flexDirection: 'row',
    width: '100%',
    backgroundColor: '#00000015',
  },
  taggedPeople: {
    color: '#e20154',
    fontSize: 16,
    marginRight: 5,
    fontWeight: 'bold',
  },

  taggedImage: {
    width: 52,
    height: 52,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#e20154',
    marginLeft: 'auto',
    alignSelf: 'flex-end',
  },

  // {/* right Container Section */}
  rightContainer: {
    // height: 300,
    gap: 9.4,
    position: 'absolute',
    // backgroundColor: 'red',
    right: 7,
    bottom: 23,
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'flex-end',
    zIndex: 10,
    // marginRight: 5,
  },
  profileImage: {
    width: 48,
    height: 48,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: '#fff',
  },
  iconContainer: {
    marginBottom: 8,
    alignItems: 'center',
  },
  iconText: {
    fontSize: 12,
    fontWeight: '500',
    marginTop: -4,
    color: '#fff',
    alignSelf: 'center',
    fontFamily: 'Overpass-Regular',
  },
  animatedView: {
    // width:  45,
    // height: 45,
    // backgroundColor: 'blue',
  },
  isHeartedImage: {
    width: 60,
    height: 60,
  },
  coverVideoLoading: {
    // backgroundColor: '#077e8c',
    height: "100%",
    width: '100%',
    // bottom: 300,
    // top: 0,
    // left: 0,
    // right: 0,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 20,
    zIndex: 80,
  },
  coverMain: {
    flex: 1,
    width: '100%',
    heigth: '100%',
    backgroundColor: '#000',
  },
  activityCover: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    top: 0,
    left: 0,
    backgroundColor: '#0a171e53',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  hidden: {
    width: 0,
    height: 0,
    opacity: 0,
  },
});
