import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  roundImage: {
    width: 32,
    height: 32,
    borderRadius: 50
  },
  styleLandingLogo: {
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00000088',
  },
  coverHere: {
    width: '100%',
    padding: 20,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00000088',
  },
  positionAbsoluteView: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    padding: 20,
  },
  whatsYourNumber: {
    fontWeight: 'bold',
    marginBottom: 30,
    fontSize: 30,
    color: '#fff',
  },
  textInputLinkCover: {
    width: '100%',
    borderRadius: 5,
    borderWidth: 2,
    backgroundColor: '#fff',
    flexDirection: 'row',
    overflow: 'hidden',
    height: 50,
    marginVertical: 10,
    alignItems: 'center',
    borderColor: '#fff',
    paddingLeft: 20,
  },
  inputTextInput: {
    paddingLeft: 20,
    color: '#3b3b3b',
    width: '100%',
    paddingRight: 15,
  },
  eachBtnCover: {
    backgroundColor: '#e20154',
    paddingHorizontal: 20,
    borderRadius: 5,
    height: 55,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  backTouchableOpacity: {
    width: 40,
    height: 40,
    borderRadius: 50,
    backgroundColor: '#0a171e',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: 40,
    top: 20,
  },
  eachBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 15,
  },
  handleComponentStyle: {
    width: '100%',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    flexDirection: 'row',
    backgroundColor: '#e20154',
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomColor: '#d1d1d1',
    borderBottomWidth: 2,
  },
  reactionText: {
    color: '#000',
    textAlign: 'center',
    fontWeight: 'bold',
  },

  showAbsolute: {
    position: 'absolute',
    backgroundColor: '#00003330',
    width: '100%',
    height: '100%',
    zIndex: 22,
  },

  closeLine: {
    position: 'absolute',
    right: 15,
    backgroundColor: '#e1e1e1',
    width: 30,
    height: 30,
    borderRadius: 20,
    alignItems: 'center',
    marginLeft: 'auto',
    justifyContent: 'center',
  },

  categoryText: {
    fontWeight: 'bold',
    fontSize: 25,
    textAlign: 'center',
    marginTop: 20,
    color: '#111',
  },
  subCategoryText: {
    color: '#9f9f9f',
    width: '80%',
    marginTop: 20,
    margin: 'auto',
    alignSelf: 'center',
    textAlign: 'center',
  },
  coverUserCommentSection: {
    width: '100%',
    height: 50,
    flexDirection: 'row',
    marginBottom: 10,
    // paddingBottom: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sortText: {
    color: '#111',
    fontSize: 16,
  },
  clickable: {
    width: 30,
    height: 30,
    borderRadius: 45,
    backgroundColor: 'blue',
    alignItems: 'center',
    justifyContent: 'center',

    borderColor: '#00000022',
    borderWidth: 1,
  },
  innerCircle: {
    width: 13,
    marginLeft: 0,
    height: 13,
    backgroundColor: '#fff',
    borderRadius: 30,
  },
});
export default styles;