import {View, Dimensions, StyleSheet} from 'react-native';
import React from 'react';

const styles = StyleSheet.create({
  // testing bottom sheet  HERE
  renderHeader: {
    // backgroundColor: '#fff',
    shadowColor: '#333',
    shadowOffset: {width: -1, height: -3},
    shadowRadius: 2,
    shadowOpacity: 0.4,
    paddingTop: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: '#f00',
  },
  panelHeader: {
    alignItems: 'center',
  },
  panelHandle: {
    width: 40,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00000040',
    marginBottom: 10,
  },
  renderInner: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
  },
  showAbsolute: {
    position: 'absolute',
    // backgroundColor: '#e010b400',
    backgroundColor: '#00003330',
    width: '100%',
    height: '100%',
    zIndex: 22,
  },
  handleComponentStyle: {
    width: '100%',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    flexDirection: 'row',
    backgroundColor: '#e20154',
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomColor: '#d1d1d1',
    borderBottomWidth: 2,
  },
  reactionText: {
    color: '#000',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  closeLine: {
    position: 'absolute',
    right: 15,
    backgroundColor: '#e1e1e1',
    width: 30,
    height: 30,
    borderRadius: 20,
    alignItems: 'center',
    marginLeft: 'auto',
    justifyContent: 'center',
  },
  sendIconCover: {
    position: 'absolute',
    right: 15,
    backgroundColor: '#e1e1e1',
    width: 42,
    height: 42,
    borderRadius: 20,
    alignItems: 'center',
    marginLeft: 'auto',
    justifyContent: 'center',
  },
  coverScrollView: {
    backgroundColor: '#efefef',
    // backgroundColor: 'red',
    height: '100%',
    padding: 20,
    paddingTop: 0,
  },
  coverUserCommentSection: {
    width: '100%',
    paddingHorizontal: 20,
    height: 60,
    backgroundColor: '#efefef',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: '#d1d1d1',
    borderBottomWidth: 2,
  },
  commentImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  commentInput: {
    width: '80%',
    color: '#000',
    // height: '100%',
    fontFamily: 'Overpass-Regular',
    marginLeft: 10,
  },
  rememberTextCover: {
    paddingHorizontal: 20,
    backgroundColor: '#cfcfcf',
    borderBottomColor: '#d1d1d1',
    height: 60,
    justifyContent: 'center',
    borderBottomWidth: 2,
  },
  rememberText: {
    color: '#003',
    fontFamily: 'Overpass-Regular',
  },
  coverMain: {
    flex: 1,
    width: '100%',
    heigth: '100%',
    backgroundColor: '#000',
  },

  activiityCover: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 80,
  },
  pleaseRetry: {
    marginTop: 20,
    color: '#0a171e',
    textAlign: 'center',
  },
  // Ionicons: {
  //   position: 'absolute',
  //   right: 20,
  // },

  activityCover: {
    width: '100%',
    height: '100%',
    backgroundColor: '#ccc',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  replyingTo: {
    // backgroundColor: '#0a171e',
    // backgroundColor: '#ffffff36',
    backgroundColor: '#efefef',
    width: '100%',
    borderRadius: 5,
    marginBottom: -7,
    // borderLeftWidth: 4,
    // borderLeftColor: '#9e005d89',
    padding: 8,
    paddingLeft: 30,
    paddingTop: 25
  },
  time: {
    alignSelf: 'flex-end',
    color: '#0a171e',
    position: 'absolute',
    top: 9,
    left: 30,
    // color: '#fff',
    fontWeight: 'bold',
    fontSize: 11,
  },
  closeCover: {
    alignSelf: 'flex-end',
    position: 'absolute',
    top: 3,
    right: 7,
    width: 40,
    height: 40,
    fontWeight: 'bold',
  },
});

export default styles;
