import { View, Dimensions, StyleSheet } from 'react-native';
import React from 'react';

const styles = StyleSheet.create({
  comment: {
    color: '#3b3b3b',
    textAlign: 'center',
    fontSize: 15,
  },
  activityCover: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  pleaseRetry: {
    marginTop: 20,
    color: '#262626',
    textAlign: 'center',
  },
  activiityCover: {
    width: '80%',
    height: '100%',
    marginLeft: 'auto',
    marginRight: 'auto',
    // justifyContent: 'center',
    alignItems: 'center',
  },

  containerCover: {
    width: '100%',
    flex: 1,
    // backgroundColor: '#fff',
  },
  profileImgCover: {
    position: 'relative',
    overflow: 'hidden',
    width: 130,
    height: 130,
    marginTop: 35,
    borderRadius: 100,
    marginLeft: 40,
  },
  profileImg: {
    display: 'flex',

    width: '100%',
    height: '100%',
    // alignSelf: 'center',
  },
  profileImgLoaderCover: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    backgroundColor: '#0a171e63',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  uploadNew: {
    marginLeft: 40,
    // textAlign: 'center',
    marginTop: 10,
    color: 'blue',
    fontWeight: '500',
    fontSize: 19,
  },
  eachNameCover: {
    borderBottomColor: '#ccc',
    borderBottomWidth: 2,
    paddingBottom: 3,
    marginTop: 10,
  },
  upperText: {
    fontFamily: 'Gilroy-Regular',
    fontSize: 13,
  },
  mainText: {
    color: '#3b3b3b',
    height: 50,
    width: '100%',
    fontSize: 20,
  },

  contentContainer: {
    backgroundColor: 'red',
  },
  viewCover: {
    width: '100%',
    height: 35,
  },
  linkSection: {
    flexDirection: 'row',
    marginTop: 20,
    alignItems: 'center',
  },
  sideText: {
    fontFamily: 'Gilroy-Regular',
    marginLeft: 'auto',
  },
  showAbsolute: {
    position: 'absolute',
    backgroundColor: '#00003330',
    width: '100%',
    height: '100%',
    zIndex: 22,
  },
  handleComponentStyle: {
    width: '100%',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    flexDirection: 'row',
    backgroundColor: '#fff',
    height: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomColor: '#d1d1d1',
    borderBottomWidth: 2,
  },
  reactionText: {
    color: '#000',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  closeLine: {
    position: 'absolute',
    right: 15,
    backgroundColor: '#e1e1e1',
    width: 30,
    height: 30,
    borderRadius: 20,
    alignItems: 'center',
    marginLeft: 'auto',
    justifyContent: 'center',
  },
  categoryText: {
    fontWeight: 'bold',
    fontSize: 25,
    textAlign: 'center',
    marginTop: 20,
    color: '#111',
  },
  subCategoryText: {
    color: '#9f9f9f',
    // fontSize: 17,
    width: '80%',
    marginTop: 20,
    margin: 'auto',
    alignSelf: 'center',
    textAlign: 'center',
  },
  coverSearchHere: {
    backgroundColor: '#efefef',
    width: '100%',
    paddingHorizontal: 20,
    borderRadius: 5,
    height: 45,
    alignItems: 'center',
    // justifyContent: 'center',
    flexDirection: 'row',
  },
  coverUserCommentSection: {
    width: '100%',
    height: 50,
    flexDirection: 'row',
    marginBottom: 10,
    // paddingBottom: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sortText: {
    color: '#111',
    fontSize: 16,
  },
  clickable: {
    width: 30,
    height: 30,
    borderRadius: 45,
    backgroundColor: 'blue',
    alignItems: 'center',
    justifyContent: 'center',

    borderColor: '#9f9f9f',
    borderWidth: 2,
  },
  innerCircle: {
    width: 13,
    marginLeft: 1,
    height: 13,
    backgroundColor: '#fff',
    borderRadius: 30,
  },
  textInputLinkCover: {
    width: '100%',
    borderRadius: 5,
    borderWidth: 2,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    borderColor: '#9f9f9f',
    paddingLeft: 20,
  },
  inputTextInput: {
    paddingLeft: 20,
    width: '100%',
    color: '#3b3b3b',
    paddingRight: 15,
    fontFamily: 'Gilroy-Regular',
    textTransform: 'lowercase',
  },
  eachBtnCover: {
    backgroundColor: '#efefef',
    paddingHorizontal: 20,
    borderRadius: 5,
    height: 55,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  eachBtnText: {
    color: '#262626',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 15,
  },
});
export default styles;
